AllCops:
  Include:
    - '**/Rakefile'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false