# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df6af36756bf5bd3b6edf5d2b27a4e830824ac608ed30921df67df766a7baaf3b6c5243c39bd5c12ef784e4de5482842606847ecebbecf2a595df25679b1988d

test:
  secret_key_base: 9d68c57b70e6c4bbbd085096f0bf503c0b24097bb06ffcc8d4a3bb6d224d6b2cfad0e30d4c227ed589d153522b289486475edfd0887b292d230eef3fdc8e5324

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
